### PR TITLE
mac thing in gitignore

### PR DESCRIPTION
**Pull request by Lochneska**

### CODE REVIEW

**Comment by klusi6** [comment]
**Very nice!**

**Review by klusi6 — APPROVED** [review]

**Review by Zvelebilm — APPROVED** [review]

**Review by BariekR — APPROVED** [review]
LGBT friendly

**Review by c3f2g2 — APPROVED** [review]
c3f2g2 Approved

**Review by PavelSlimBilek — APPROVED** [review]
Great job!

**Pull request merged**
